<BoxLayoutExplGUI>
	orientation: 'vertical'
	
	padding: 5
	spacing: 5

	canvas.before:
		Color:
			rgb: [0.22,0.22,0.22]
		Rectangle:
			pos: self.pos
	
	Button:
		text: 'A'
		size_hint: (.5, .5)
		pos_hint: {'center_x': .5}
		on_press: root.setToLabel(self.text)
	Button:
		text: 'B'
		size_hint: (.7, 1)
		pos_hint: {'center_x': .6}
		on_press: root.setToLabel(self.text)
	Label:
		id: label_1
		text: 'label 1'
		size_hint: (1, 2)
		